window.__LAB_ACTIVITIES__ = {
  "generated_at": "2026-05-13T11:46:49.513Z",
  "photos": [
    {
      "id": "A001",
      "category": "outdoor",
      "title_en": "Team Building Outing",
      "title_zh": "团建户外活动",
      "location_en": "Beijing Suburb",
      "location_zh": "北京郊区",
      "date": "2024-06",
      "photographer": "",
      "image": "team-building/imgs/00001.jpg",
      "height": 420
    },
    {
      "id": "A002",
      "category": "outdoor",
      "title_en": "Climbing Xiangshan Group Photo",
      "title_zh": "香山爬山小组合照",
      "location_en": "Xiangshan, Beijing",
      "location_zh": "北京香山",
      "date": "2024-01",
      "photographer": "",
      "image": "team-building/imgs/00002.jpg",
      "height": 300
    },
    {
      "id": "A003",
      "category": "outdoor",
      "title_en": "Hiking Trip",
      "title_zh": "爬山团建",
      "location_en": "Fragrant Hills, Beijing",
      "location_zh": "北京香山",
      "date": "2024-04",
      "photographer": "",
      "image": "team-building/imgs/00003.jpg",
      "height": 360
    },
    {
      "id": "A004",
      "category": "outdoor",
      "title_en": "Research Retreat",
      "title_zh": "学术研讨营",
      "location_en": "Beijing",
      "location_zh": "北京",
      "date": "2024-09",
      "photographer": "",
      "image": "team-building/imgs/00004.jpg",
      "height": 500
    },
    {
      "id": "A005",
      "category": "outdoor",
      "title_en": "Yang Ge Solo Photo at Xiangshan",
      "title_zh": "香山团建 杨戈单人照",
      "location_en": "Xiangshan, Beijing",
      "location_zh": "北京香山",
      "date": "2024-12",
      "photographer": "",
      "image": "team-building/imgs/00005.jpg",
      "height": 280
    },
    {
      "id": "A006",
      "category": "outdoor",
      "title_en": "Summer Barbecue",
      "title_zh": "夏日烧烤",
      "location_en": "Beijing",
      "location_zh": "北京",
      "date": "2024-07",
      "photographer": "",
      "image": "team-building/imgs/00006.jpg",
      "height": 430
    },
    {
      "id": "A007",
      "category": "outdoor",
      "title_en": "Group Photo",
      "title_zh": "实验室合照",
      "location_en": "Beihang University",
      "location_zh": "北京航空航天大学",
      "date": "2024-05",
      "photographer": "",
      "image": "team-building/imgs/00007.jpg",
      "height": 340
    },
    {
      "id": "A008",
      "category": "outdoor",
      "title_en": "Sports Day",
      "title_zh": "运动会",
      "location_en": "Beihang University",
      "location_zh": "北京航空航天大学",
      "date": "2024-10",
      "photographer": "",
      "image": "team-building/imgs/00008.jpg",
      "height": 520
    },
    {
      "id": "A009",
      "category": "outdoor",
      "title_en": "Listen to Offline Stand-up Comedy",
      "title_zh": "听线下脱口秀",
      "location_en": "Beijing, China",
      "location_zh": "北京, 中国",
      "date": "2024-02",
      "photographer": "",
      "image": "team-building/imgs/00009.jpg",
      "height": 400
    },
    {
      "id": "A010",
      "category": "meal",
      "title_en": "Hotpot Gathering",
      "title_zh": "火锅聚餐",
      "location_en": "Beijing Happy Hotpot",
      "location_zh": "北京高兴火锅",
      "date": "2024-11",
      "photographer": "",
      "image": "team-building/imgs/00010.jpg",
      "height": 450
    },
    {
      "id": "A011",
      "category": "meal",
      "title_en": "Welcome Party",
      "title_zh": "新生欢迎晚会",
      "location_en": "Beihang University",
      "location_zh": "北京航空航天大学",
      "date": "2024-09",
      "photographer": "",
      "image": "team-building/imgs/00011.jpg",
      "height": 300
    },
    {
      "id": "A012",
      "category": "meal",
      "title_en": "Dinner Gathering",
      "title_zh": "年终聚餐",
      "location_en": "Beijing",
      "location_zh": "北京",
      "date": "2024-12",
      "photographer": "",
      "image": "team-building/imgs/00012.jpg",
      "height": 390
    },
    {
      "id": "A013",
      "category": "meal",
      "title_en": "Dinner Gathering",
      "title_zh": "年终聚餐",
      "location_en": "Beijing",
      "location_zh": "北京",
      "date": "2024-12",
      "photographer": "",
      "image": "team-building/imgs/00013.jpg",
      "height": 520
    }
  ]
};
