window.__LAB_PEOPLE__ = {
  "generated_at": "2026-05-13T07:04:00.196Z",
  "members": [
    {
      "id": "M000",
      "name_en": "Liu Xianglong",
      "name_zh": "刘祥龙",
      "role_en": "Professor",
      "role_zh": "教授",
      "team": "faculty",
      "research_en": "",
      "research_zh": "",
      "photo": "imgs/Liu Xianglong.jpg",
      "email": "xlliu@buaa.edu.cn",
      "github": "",
      "scholar": "",
      "homepage": "https://xlliu-beihang.github.io/",
      "note_en": "",
      "note_zh": ""
    },
    {
      "id": "M001",
      "name_en": "Guo Jinyang",
      "name_zh": "郭晋阳",
      "role_en": "Assistant Professor",
      "role_zh": "助理教授",
      "team": "faculty",
      "research_en": "Model efficiency, data efficiency, neuromorphic computing, AI4Science",
      "research_zh": "模型压缩与高效化，数据效率，神经形态计算，AI4Science",
      "photo": "imgs/Guo Jinyang.jpg",
      "email": "jinyangguo@buaa.edu.cn",
      "github": "",
      "scholar": "https://scholar.google.com/citations?user=uJGeT1AAAAAJ&hl=zh-CN",
      "homepage": "https://jinyangguo.github.io/",
      "note_en": "",
      "note_zh": ""
    },
    {
      "id": "M002",
      "name_en": "Zheng Xingyu",
      "name_zh": "郑星宇",
      "role_en": "PhD Student",
      "role_zh": "博士研究生",
      "team": "team1",
      "research_en": "Model compression, efficient inference",
      "research_zh": "模型压缩，高效推理",
      "photo": "",
      "email": "",
      "github": "",
      "scholar": "",
      "homepage": "",
      "note_en": "",
      "note_zh": ""
    },
    {
      "id": "M003",
      "name_en": "Wang Zining",
      "name_zh": "王梓宁",
      "role_en": "PhD Student",
      "role_zh": "博士研究生",
      "team": "team1",
      "research_en": "Model compression, quantization",
      "research_zh": "模型压缩，量化",
      "photo": "imgs/Wang Zining.jpg",
      "email": "",
      "github": "",
      "scholar": "",
      "homepage": "",
      "note_en": "",
      "note_zh": ""
    },
    {
      "id": "M004",
      "name_en": "Ding Yifu",
      "name_zh": "丁一芙",
      "role_en": "PhD Student",
      "role_zh": "博士研究生",
      "team": "team1",
      "research_en": "LLM compression, post-training quantization, efficient deployment",
      "research_zh": "大语言模型压缩，训练后量化，高效部署",
      "photo": "imgs/Ding Yifu.jpg",
      "email": "yifuding@buaa.edu.cn",
      "github": "https://github.com/yifu-ding",
      "scholar": "https://scholar.google.com/citations?user=RCEI1r0AAAAJ",
      "homepage": "https://yifu-ding.github.io/",
      "note_en": "",
      "note_zh": ""
    },
    {
      "id": "M005",
      "name_en": "Yang Ge",
      "name_zh": "杨戈",
      "role_en": "Master's Student",
      "role_zh": "硕士研究生",
      "team": "team1",
      "research_en": "Efficient deep learning, model sparsity",
      "research_zh": "高效深度学习，模型稀疏化",
      "photo": "imgs/Yang Ge.jpg",
      "email": "",
      "github": "",
      "scholar": "",
      "homepage": "",
      "note_en": "",
      "note_zh": ""
    },
    {
      "id": "M006",
      "name_en": "Jin Shenghao",
      "name_zh": "金圣浩",
      "role_en": "Master's Student",
      "role_zh": "硕士研究生",
      "team": "team1",
      "research_en": "Neural network acceleration, hardware-aware optimization",
      "research_zh": "神经网络加速，硬件感知优化",
      "photo": "",
      "email": "",
      "github": "",
      "scholar": "",
      "homepage": "",
      "note_en": "",
      "note_zh": ""
    },
    {
      "id": "M007",
      "name_en": "Chen Yuanming",
      "name_zh": "陈远明",
      "role_en": "Master's Student",
      "role_zh": "硕士研究生",
      "team": "team1",
      "research_en": "Knowledge distillation, efficient training",
      "research_zh": "知识蒸馏，高效训练",
      "photo": "",
      "email": "",
      "github": "",
      "scholar": "",
      "homepage": "",
      "note_en": "",
      "note_zh": ""
    },
    {
      "id": "M008",
      "name_en": "Zeng Yejun",
      "name_zh": "曾烨均",
      "role_en": "PhD Student",
      "role_zh": "博士研究生",
      "team": "team2",
      "research_en": "Diffusion model compression, generative model efficiency",
      "research_zh": "扩散模型压缩，生成模型效率",
      "photo": "",
      "email": "",
      "github": "",
      "scholar": "",
      "homepage": "",
      "note_en": "",
      "note_zh": ""
    },
    {
      "id": "M009",
      "name_en": "Wang Jiacheng",
      "name_zh": "王家诚",
      "role_en": "PhD Student",
      "role_zh": "博士研究生",
      "team": "team2",
      "research_en": "Large model fine-tuning, parameter efficiency",
      "research_zh": "大模型微调，参数高效方法",
      "photo": "",
      "email": "",
      "github": "",
      "scholar": "",
      "homepage": "",
      "note_en": "",
      "note_zh": ""
    },
    {
      "id": "M010",
      "name_en": "Liu Xiaoning",
      "name_zh": "刘晓宁",
      "role_en": "Master's Student",
      "role_zh": "硕士研究生",
      "team": "team2",
      "research_en": "Vision model compression, efficient segmentation",
      "research_zh": "视觉模型压缩，高效分割",
      "photo": "",
      "email": "",
      "github": "",
      "scholar": "",
      "homepage": "",
      "note_en": "",
      "note_zh": ""
    },
    {
      "id": "M011",
      "name_en": "Ge Xiaoze",
      "name_zh": "葛笑泽",
      "role_en": "Master's Student",
      "role_zh": "硕士研究生",
      "team": "team2",
      "research_en": "Quantization-aware training, low-bit networks",
      "research_zh": "量化感知训练，低比特网络",
      "photo": "imgs/Ge Xiaoze.jpg",
      "email": "",
      "github": "",
      "scholar": "",
      "homepage": "",
      "note_en": "",
      "note_zh": ""
    },
    {
      "id": "M012",
      "name_en": "Weng Chenhao",
      "name_zh": "翁晨皓",
      "role_en": "Master's Student",
      "role_zh": "硕士研究生",
      "team": "team2",
      "research_en": "Efficient transformers, attention optimization",
      "research_zh": "高效 Transformer，注意力机制优化",
      "photo": "",
      "email": "",
      "github": "",
      "scholar": "",
      "homepage": "",
      "note_en": "",
      "note_zh": ""
    },
    {
      "id": "M019",
      "name_en": "Du Jinyang",
      "name_zh": "杜金阳",
      "role_en": "Master's Student",
      "role_zh": "硕士研究生",
      "team": "team2",
      "research_en": "Model compression, efficient inference",
      "research_zh": "模型压缩，高效推理",
      "photo": "",
      "email": "",
      "github": "",
      "scholar": "",
      "homepage": "",
      "note_en": "Co-supervised with Prof. Xianglong Liu",
      "note_zh": "与刘祥龙教授联合培养"
    },
    {
      "id": "M013",
      "name_en": "Xie Hui",
      "name_zh": "谢辉",
      "role_en": "PhD Student",
      "role_zh": "博士研究生",
      "team": "team3",
      "research_en": "Neuromorphic computing, spiking neural networks",
      "research_zh": "神经形态计算，脉冲神经网络",
      "photo": "imgs/Xie Hui.jpg",
      "email": "",
      "github": "",
      "scholar": "",
      "homepage": "",
      "note_en": "",
      "note_zh": ""
    },
    {
      "id": "M014",
      "name_en": "Shi Tong",
      "name_zh": "石通",
      "role_en": "Master's Student",
      "role_zh": "硕士研究生",
      "team": "team3",
      "research_en": "Spiking neural networks, brain-inspired AI",
      "research_zh": "脉冲神经网络，类脑人工智能",
      "photo": "",
      "email": "",
      "github": "",
      "scholar": "",
      "homepage": "",
      "note_en": "",
      "note_zh": ""
    },
    {
      "id": "M015",
      "name_en": "Ye Jingtao",
      "name_zh": "叶京涛",
      "role_en": "Master's Student",
      "role_zh": "硕士研究生",
      "team": "team3",
      "research_en": "AI4Science, scientific computing",
      "research_zh": "AI4科学，科学计算",
      "photo": "",
      "email": "",
      "github": "",
      "scholar": "",
      "homepage": "",
      "note_en": "",
      "note_zh": ""
    },
    {
      "id": "M016",
      "name_en": "Zhu Yanan",
      "name_zh": "朱亚男",
      "role_en": "PhD Student",
      "role_zh": "博士研究生",
      "team": "team3",
      "research_en": "Label efficiency, semi-supervised learning",
      "research_zh": "标签效率，半监督学习",
      "photo": "",
      "email": "",
      "github": "",
      "scholar": "",
      "homepage": "",
      "note_en": "",
      "note_zh": ""
    },
    {
      "id": "M017",
      "name_en": "Cui Yifan",
      "name_zh": "崔逸凡",
      "role_en": "Master's Student",
      "role_zh": "硕士研究生",
      "team": "team3",
      "research_en": "Data-efficient learning, few-shot learning",
      "research_zh": "数据高效学习，小样本学习",
      "photo": "",
      "email": "",
      "github": "",
      "scholar": "",
      "homepage": "",
      "note_en": "",
      "note_zh": ""
    },
    {
      "id": "M018",
      "name_en": "Xiao Peng",
      "name_zh": "肖鹏",
      "role_en": "Master's Student",
      "role_zh": "硕士研究生",
      "team": "team3",
      "research_en": "Efficient multimodal models, vision-language compression",
      "research_zh": "高效多模态模型，视觉语言模型压缩",
      "photo": "",
      "email": "",
      "github": "",
      "scholar": "",
      "homepage": "",
      "note_en": "",
      "note_zh": ""
    },
    {
      "id": "MA01",
      "name_en": "He Changyi",
      "name_zh": "何昌义",
      "role_en": "Alumni · Master's Student",
      "role_zh": "校友 · 硕士",
      "team": "alumni",
      "research_en": "Model compression, efficient deep learning",
      "research_zh": "模型压缩，高效深度学习",
      "photo": "",
      "email": "",
      "github": "",
      "scholar": "",
      "homepage": "",
      "note_en": "Master 2023–2025; ICML2025; National Scholarship · Next: Ant Group (SP Offer)",
      "note_zh": "硕士 2023–2025；ICML2025；国家奖学金 · 下一站：蚂蚁集团 SP Offer"
    },
    {
      "id": "MA02",
      "name_en": "Gao Shengbo",
      "name_zh": "高圣博",
      "role_en": "Alumni · Research Intern",
      "role_zh": "校友 · 研究实习生",
      "team": "alumni",
      "research_en": "Model compression, efficient training",
      "research_zh": "模型压缩，高效训练",
      "photo": "",
      "email": "",
      "github": "",
      "scholar": "",
      "homepage": "",
      "note_en": "Intern from Beihang University; AAAI2026 · Next: Ph.D. at ELLIS Institute Finland",
      "note_zh": "北航实习生；AAAI2026 · 下一站：ELLIS研究所博士"
    },
    {
      "id": "MA03",
      "name_en": "Chen Hong",
      "name_zh": "陈鸿",
      "role_en": "Alumni · Master's Student",
      "role_zh": "校友 · 硕士",
      "team": "alumni",
      "research_en": "Vision-language models, model compression",
      "research_zh": "视觉语言模型，模型压缩",
      "photo": "",
      "email": "",
      "github": "",
      "scholar": "",
      "homepage": "",
      "note_en": "CVPR2024, ACM MM2024, ACL2024; National Scholarship · Next: Alibaba (Ali Star)",
      "note_zh": "CVPR2024, ACM MM2024, ACL2024；国家奖学金 · 下一站：阿里巴巴阿里星"
    },
    {
      "id": "MA04",
      "name_en": "Lv Chengtao",
      "name_zh": "吕程涛",
      "role_en": "Alumni · Master's Student",
      "role_zh": "校友 · 硕士",
      "team": "alumni",
      "research_en": "LLM compression, multimodal compression",
      "research_zh": "大模型压缩，多模态压缩",
      "photo": "",
      "email": "",
      "github": "",
      "scholar": "",
      "homepage": "",
      "note_en": "CVPR2024, ACM MM2024; National Scholarship · Next: Ph.D. at Nanyang Technological University",
      "note_zh": "CVPR2024, ACM MM2024；国家奖学金 · 下一站：南洋理工大学博士"
    },
    {
      "id": "MA05",
      "name_en": "Wu Jianyu",
      "name_zh": "吴健宇",
      "role_en": "Alumni · Undergraduate Intern",
      "role_zh": "校友 · 本科实习生",
      "team": "alumni",
      "research_en": "Efficient LLM training, reasoning",
      "research_zh": "高效大模型训练，推理",
      "photo": "",
      "email": "",
      "github": "",
      "scholar": "",
      "homepage": "",
      "note_en": "Intern from Beihang University; ICML2024 · Next: Joint Ph.D. at SJTU & Shanghai AI Lab",
      "note_zh": "北航本科实习生；ICML2024 · 下一站：上海交通大学&上海AI Lab联培博士"
    }
  ]
};
