window.__LAB_PAPERS__ = {
  "generated_at": "2026-05-13T11:24:36.950Z",
  "papers": [
    {
      "id": "P001",
      "group": "Books",
      "title": "Generalizing from Limited Resources in the Open World",
      "authors": "Jinyang Guo, Yuqing Ma, Yifu Ding, Ruihao Gong, Xingyu Zheng, Changyi He, Yantao Lu, Xianglong Liu",
      "venue": "Communications in Computer and Information Science",
      "year": 2026,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "",
      "code_link": "",
      "book_link": "https://link.springer.com/book/10.1007/978-981-97-6125-8",
      "award": "",
      "tags": "Book", 
      "featured": true,
      "cover_image": ""
    },
    {
      "id": "P002",
      "group": "2026",
      "title": "CMedBench: Comprehensive Evaluation of the LLM Compression Impact on Medical Applications",
      "authors": "Shengbo Gao, Jinyang Guo✉, Lixian Su, Yifu Ding, Shiqiao Gu, Aishan Liu, Yuqing Ma, Zhiwang Zhang, Xianglong Liu",
      "venue": "The AAAI Conference on Artificial Intelligence (AAAI), 2026.",
      "year": 2026,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://ojs.aaai.org/index.php/AAAI/article/view/39264",
      "code_link": "",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": "imgs/cmedbench.jpg", 
      "tags": "Medical, Benchmark, LLM Compression",
      "intro_md_cn": "publications/md/CMedBench_summary_cn.md", 
      "intro_md_en": "publications/md/CMedBench_summary_en.md"
    },
    {
      "id": "P003",
      "group": "2025",
      "title": "SLMQuant: Benchmarking Small Language Model Quantization for Practical Deployment",
      "authors": "Jiacheng Wang, Yejun Zeng, Jinyang Guo✉, Yuqing Ma, Aishan Liu, Xianglong Liu",
      "venue": "ACM MM 2025 Workshop on RichMediaGAI",
      "year": 2025,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://dl.acm.org/doi/abs/10.1145/3746262.3761973",
      "code_link": "",
      "book_link": "",
      "award": "Best Paper Award",
      "featured": true,
      "cover_image": ""
    },
    {
      "id": "P004",
      "group": "2025",
      "title": "大语言模型压缩综述",
      "authors": "Jinyang Guo (郭晋阳), Changyi He (贺昌义), Ge Yang (杨戈), Xianglong Liu (刘祥龙)",
      "venue": "《计算机科学与探索》2025.",
      "year": 2025,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "",
      "code_link": "",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": "imgs/llm-quant-survey.png"
    },
    {
      "id": "P005",
      "group": "2025",
      "title": "AGENTSAFE: Benchmarking the Safety of Embodied Agents on Hazardous Instructions",
      "authors": "Aishan Liu, Zonghao Ying, Le Wang, Junjie Mu, Jinyang Guo, Jiakai Wang, Yuqing Ma, Siyuan Liang, Mingchuan Zhang, Xianglong Liu, Dacheng Tao",
      "venue": "ICML 2025 Workshop on MAS",
      "year": 2025,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://arxiv.org/pdf/2506.14697",
      "code_link": "",
      "book_link": "",
      "award": "Outstanding Paper Award",
      "featured": true,
      "cover_image": ""
    },
    {
      "id": "P006",
      "group": "2025",
      "title": "DA-KD: Difficulty-Aware Knowledge Distillation for Efficient Large Language Models",
      "authors": "Changyi He, Yifu Ding, Jinyang Guo✉, Ruihao Gong, Haotong Qin, Xianglong Liu",
      "venue": "Forty-second International Conference on Machine Learning (ICML), 2025.",
      "year": 2025,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://icml.cc/virtual/2025/poster/45516",
      "code_link": "",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": "imgs/da-kd.png"
    },
    {
      "id": "P007",
      "group": "2025",
      "title": "Pushing the Limit of Post-Training Quantization",
      "authors": "Ruihao Gong, Xianglong Liu, Yuhang Li, Yunqiang Fan, Xiuying Wei, Jinyang Guo",
      "venue": "IEEE Transactions on Pattern Analysis and Machine Intelligence (TPAMI), 2025.",
      "year": 2025,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://ieeexplore.ieee.org/abstract/document/10938638",
      "code_link": "https://github.com/ModelTC/MQBench/",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": ""
    },
    {
      "id": "P008",
      "group": "2024",
      "title": "LLMCBench: Benchmarking Large Language Model Compression for Efficient Deployment",
      "authors": "Ge Yang, Changyi He, Jinyang Guo✉, Jianyu Wu, Yifu Ding, Aishan Liu, Haotong Qin, Pengliang Ji, Xianglong Liu",
      "venue": "Annual Conference on Neural Information Processing Systems (NeurIPS D&B Track, Spotlight), 2024.",
      "year": 2024,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://arxiv.org/pdf/2410.21352",
      "code_link": "https://github.com/AboveParadise/LLMCBench/",
      "book_link": "",
      "award": "Spotlight",
      "featured": true,
      "cover_image": ""
    },
    {
      "id": "P009",
      "group": "2024",
      "title": "BiDM: Pushing the Limit of Quantization for Diffusion Models",
      "authors": "Xingyu Zheng, Xianglong Liu, Yichen Bian, Xudong Ma, Yulun Zhang, Jiakai Wang, Jinyang Guo, Haotong Qin",
      "venue": "Annual Conference on Neural Information Processing Systems (NeurIPS), 2024.",
      "year": 2024,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://openreview.net/pdf?id=oWAItGB8LJ",
      "code_link": "",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": ""
    },
    {
      "id": "P010",
      "group": "2024",
      "title": "DDK: Distilling Domain Knowledge for Efficient Large Language Models",
      "authors": "Jiaheng Liu, Chenchen Zhang, Jinyang Guo, Yuanxing Zhang, Haoran Que, Ken Deng, Zhiqi Bai, Jie Liu, Ge Zhang, Jiakai Wang, Yanan Wu, Congnan Liu, Wenbo Su, Jiamang Wang, Lin Qu, Bo Zheng",
      "venue": "Annual Conference on Neural Information Processing Systems (NeurIPS), 2024.",
      "year": 2024,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://arxiv.org/abs/2407.16154",
      "code_link": "",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": ""
    },
    {
      "id": "P011",
      "group": "2024",
      "title": "QVD: Post-training Quantization for Video Diffusion Models",
      "authors": "Shilong Tian, Hong Chen, Chengtao Lv, Yu Liu, Jinyang Guo✉, Xianglong Liu, Shengxi Li, Hao Yang, Tao Xie",
      "venue": "ACM MULTIMEDIA (ACM MM), 2024.",
      "year": 2024,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://arxiv.org/pdf/2407.11585",
      "code_link": "",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": ""
    },
    {
      "id": "P012",
      "group": "2024",
      "title": "VRDistill: Vote Refinement Distillation for Efficient Indoor 3D Object Detection",
      "authors": "Ze Yuan*, Jinyang Guo*, Dakai An, Junran Wu, He Zhu, Jianhao Li, Xueyuan Chen, Ke Xu, Jiaheng Liu",
      "venue": "ACM MULTIMEDIA (ACM MM), 2024.",
      "year": 2024,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://openreview.net/pdf?id=Pmtk0LWaXu",
      "code_link": "",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": ""
    },
    {
      "id": "P013",
      "group": "2024",
      "title": "PTSBench: A Comprehensive Post-Training Sparsity Benchmark Towards Algorithms and Models",
      "authors": "Zining Wang, Jinyang Guo✉, Ruihao Gong, Yang Yong, Aishan Liu, Yushi Huang, Jiaheng Liu, Xianglong Liu",
      "venue": "ACM MULTIMEDIA 2024 (ACM MM), 2024.",
      "year": 2024,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://openreview.net/forum?id=UdAcn64u5f",
      "code_link": "https://github.com/ModelTC/msbench",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": ""
    },
    {
      "id": "P014",
      "group": "2024",
      "title": "Compressing Large Language Models by Joint Sparsification and Quantization",
      "authors": "Jinyang Guo, Jianyu Wu, Zining Wang, Jiaheng Liu, Ge Yang, Yifu Ding, Ruihao Gong, Haotong Qin, Xianglong Liu",
      "venue": "Forty-first International Conference on Machine Learning (ICML), 2024.",
      "year": 2024,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://openreview.net/pdf?id=sCGRhnuMUJ",
      "code_link": "https://github.com/uanu2002/JSQ",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": "imgs/compression-large-language-models.png"
    },
    {
      "id": "P015",
      "group": "2024",
      "title": "LTA-PCS: Learnable Task-Agnostic Point Cloud Sampling",
      "authors": "Jiaheng Liu, Jianhao Li, Kaisiyuan Wang, Hongcheng Guo, Jian Yang, Junran Peng, Ke Xu, Xianglong Liu, Jinyang Guo✉",
      "venue": "IEEE Conference on Computer Vision and Pattern Recognition (CVPR), 2024.",
      "year": 2024,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://ieeexplore.ieee.org/abstract/document/10130783",
      "code_link": "",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": ""
    },
    {
      "id": "P016",
      "group": "2024",
      "title": "PTQ4SAM: Post-Training Quantization for Segment Anything",
      "authors": "Chengtao Lv, Hong Chen, Jinyang Guo✉, Yifu Ding, Xianglong Liu",
      "venue": "IEEE Conference on Computer Vision and Pattern Recognition (CVPR), 2024.",
      "year": 2024,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://ieeexplore.ieee.org/abstract/document/10130783",
      "code_link": "https://github.com/chengtao-lv/PTQ4SAM",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": "imgs/ptq4sam.png"
    },
    {
      "id": "P017",
      "group": "2024",
      "title": "Reg-PTQ: Regression-specialized Post-training Quantization for Fully Quantized Object Detector",
      "authors": "Yifu Ding, Weilun Feng, Chuyan Chen, Jinyang Guo, Xianglong Liu",
      "venue": "IEEE Conference on Computer Vision and Pattern Recognition (CVPR), 2024.",
      "year": 2024,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://openaccess.thecvf.com/content/CVPR2024/papers/Ding_Reg-PTQ_Regression-specialized_Post-training_Quantization_for_Fully_Quantized_Object_Detector_CVPR_2024_paper.pdf",
      "code_link": "",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": "imgs/reg-ptq.png"
    },
    {
      "id": "P018",
      "group": "2024",
      "title": "Fast and Controllable Post-training Sparsity: Learning Optimal Sparsity Allocation with Global Constraint in Minutes",
      "authors": "Ruihao Gong, Yang Yong, Zining Wang, Jinyang Guo, Xiuying Wei, Yuqing Ma, Xianglong Liu",
      "venue": "The AAAI Conference on Artificial Intelligence (AAAI), 2024.",
      "year": 2024,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://arxiv.org/abs/2405.05808",
      "code_link": "",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": ""
    },
    {
      "id": "P019",
      "group": "2024",
      "title": "DB-LLM: Accurate Dual-Binarization for Efficient LLMs",
      "authors": "Hong Chen, Chengtao Lv, Liang Ding, Haotong Qin, Xiabin Zhou, Yifu Ding, Xuebo Liu, Min Zhang, Jinyang Guo, Xianglong Liu, Dacheng Tao",
      "venue": "Findings of the Association for Computational Linguistics (ACL Findings), 2024.",
      "year": 2024,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://arxiv.org/abs/2402.11960",
      "code_link": "",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": "imgs/db-llm.png"
    },
    {
      "id": "P020",
      "group": "2023",
      "title": "Multidimensional Pruning and Its Extension: A Unified Framework for Model Compression",
      "authors": "Jinyang Guo, Dong Xu, and Wanli Ouyang",
      "venue": "IEEE Transactions on Neural Networks and Learning Systems (TNNLS), 2023.",
      "year": 2023,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://ieeexplore.ieee.org/abstract/document/10130783",
      "code_link": "",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": ""
    },
    {
      "id": "P021",
      "group": "2023",
      "title": "CBANet: Toward Complexity and Bitrate Adaptive Deep Image Compression Using a Single Network",
      "authors": "Jinyang Guo, Dong Xu, and Guo Lu",
      "venue": "IEEE Transactions on Image Processing (TIP), 2023.",
      "year": 2023,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://ieeexplore.ieee.org/document/10061458",
      "code_link": "https://github.com/JinyangGuo/CBANet-release",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": ""
    },
    {
      "id": "P022",
      "group": "2023",
      "title": "Outlier Suppression+: Accurate Quantization of Large Language Models by Equivalent and Optimal Shifting and Scaling",
      "authors": "Xiuying Wei, Yunchen Zhang, Yuhang Li, Xiangguo Zhang, Ruihao Gong, Jinyang Guo, Xianglong Liu",
      "venue": "Conference on Empirical Methods in Natural Language Processing (EMNLP), 2023.",
      "year": 2023,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://arxiv.org/abs/2304.09145",
      "code_link": "https://github.com/ModelTC/Outlier_Suppression_Plus",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": ""
    },
    {
      "id": "P023",
      "group": "2023",
      "title": "Adaptive Contrastive Knowledge Distillation for BERT Compression",
      "authors": "Jinyang Guo, Jiaheng Liu, Zining Wang, Yuqing Ma, Ruihao Gong, Ke Xu, Xianglong Liu",
      "venue": "Findings of the Association for Computational Linguistics (ACL Findings), 2023.",
      "year": 2023,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://aclanthology.org/2023.findings-acl.569/",
      "code_link": "",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": ""
    },
    {
      "id": "P024",
      "group": "2023",
      "title": "Annealing-based Label-transfer Learning for Open World Object Detection",
      "authors": "Yuqing Ma, Hainan Li, Zhange Zhang, Jinyang Guo, Shanghang Zhang, Ruihao Gong, Xianglong Liu",
      "venue": "IEEE Conference on Computer Vision and Pattern Recognition (CVPR), 2023.",
      "year": 2023,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://openaccess.thecvf.com/content/CVPR2023/html/Ma_Annealing-Based_Label-Transfer_Learning_for_Open_World_Object_Detection_CVPR_2023_paper.html",
      "code_link": "",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": ""
    },
    {
      "id": "P025",
      "group": "2023",
      "title": "Automatic Loss Function Search for Adversarial Unsupervised Domain Adaptation",
      "authors": "Zhen Mei, Peng Ye, Hancheng Ye, Baopu Li, Jinyang Guo, Tao Chen, Wanli Ouyang",
      "venue": "IEEE Transactions on Circuits and Systems for Video Technology (TCSVT), 2023.",
      "year": 2023,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://ieeexplore.ieee.org/document/10078330/",
      "code_link": "",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": ""
    },
    {
      "id": "P026",
      "group": "2022",
      "title": "APSNet: Toward Adaptive Point Sampling for Efficient 3D Action Recognition",
      "authors": "Jiaheng Liu*, Jinyang Guo*, Dong Xu",
      "venue": "IEEE Transactions on Image Processing (TIP), 2022.",
      "year": 2022,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://ieeexplore.ieee.org/abstract/document/9844448",
      "code_link": "",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": ""
    },
    {
      "id": "P027",
      "group": "2022",
      "title": "3D-pruning: A Model Compression Framework for Efficient 3D Action Recognition",
      "authors": "Jinyang Guo, Jiaheng Liu, Dong Xu",
      "venue": "IEEE Transactions on Circuits and Systems for Video Technology (TCSVT), 2022.",
      "year": 2022,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://ieeexplore.ieee.org/abstract/document/9852466",
      "code_link": "",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": ""
    },
    {
      "id": "P028",
      "group": "2022",
      "title": "Coupleface: Relation Matters for Face Recognition Distillation",
      "authors": "Jiaheng Liu, Haoyu Qin, Yichao Wu, Jinyang Guo, Ding Liang, Ke Xu",
      "venue": "European Conference on Computer Vision (ECCV), 2022.",
      "year": 2022,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://link.springer.com/chapter/10.1007/978-3-031-19775-8_40",
      "code_link": "",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": ""
    },
    {
      "id": "P029",
      "group": "2022",
      "title": "Geometrymotion-transformer: An End-to-end Framework for 3D Action Recognition",
      "authors": "Jiaheng Liu*, Jinyang Guo*, Dong Xu",
      "venue": "IEEE Transactions on Multimedia (TMM), 2022.",
      "year": 2022,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://ieeexplore.ieee.org/abstract/document/9854132",
      "code_link": "",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": ""
    },
    {
      "id": "P030",
      "group": "2022",
      "title": "Coarse-to-fine Deep Video Coding with Hyperprior-guided Mode Prediction",
      "authors": "Zhihao Hu, Guo Lu, Jinyang Guo, Shan Liu, Wei Jiang, Dong Xu",
      "venue": "IEEE Conference on Computer Vision and Pattern Recognition (CVPR), 2022.",
      "year": 2022,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "http://openaccess.thecvf.com/content/CVPR2022/html/Hu_Coarse-To-Fine_Deep_Video_Coding_With_Hyperprior-Guided_Mode_Prediction_CVPR_2022_paper.html",
      "code_link": "",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": ""
    },
    {
      "id": "P031",
      "group": "2022",
      "title": "Unsupervised Learning of Accurate Siamese Tracking",
      "authors": "Qiuhong Shen, Lei Qiao, Jinyang Guo, Peixia Li, Xin Li, Bo Li, Weitao Feng, Weihao Gan, Wei Wu, Wanli Ouyang",
      "venue": "IEEE Conference on Computer Vision and Pattern Recognition (CVPR), 2022.",
      "year": 2022,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "http://openaccess.thecvf.com/content/CVPR2022/html/Shen_Unsupervised_Learning_of_Accurate_Siamese_Tracking_CVPR_2022_paper.html",
      "code_link": "",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": ""
    },
    {
      "id": "P032",
      "group": "2020-2021",
      "title": "JointPruning: Pruning Networks along Multiple Dimensions for Efficient Point Cloud Processing",
      "authors": "Jinyang Guo, Jiaheng Liu, Dong Xu",
      "venue": "IEEE Transactions on Circuits and Systems for Video Technology (TCSVT), 2021.",
      "year": 2021,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://ieeexplore.ieee.org/abstract/document/9516010",
      "code_link": "",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": ""
    },
    {
      "id": "P033",
      "group": "2020-2021",
      "title": "Transformer3D-Det: Improving 3D Object Detection by Vote Refinement",
      "authors": "Lichen Zhao*, Jinyang Guo*, Dong Xu, Lu Sheng",
      "venue": "IEEE Transactions on Circuits and Systems for Video Technology (TCSVT), 2021.",
      "year": 2021,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://ieeexplore.ieee.org/abstract/document/9504551",
      "code_link": "",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": ""
    },
    {
      "id": "P034",
      "group": "2020-2021",
      "title": "Model Compression using Progressive Channel Pruning",
      "authors": "Jinyang Guo, Weichen Zhang, Wanli Ouyang, Dong Xu",
      "venue": "IEEE Transactions on Circuits and Systems for Video Technology (TCSVT), 2020.",
      "year": 2020,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://ieeexplore.ieee.org/abstract/document/9097925/",
      "code_link": "",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": ""
    },
    {
      "id": "P035",
      "group": "2020-2021",
      "title": "Channel Pruning Guided by Classification Loss and Feature Importance",
      "authors": "Jinyang Guo, Wanli Ouyang, Dong Xu",
      "venue": "The AAAI Conference on Artificial Intelligence (AAAI), 2020.",
      "year": 2020,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://aaai.org/ojs/index.php/AAAI/article/view/6720",
      "code_link": "",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": ""
    },
    {
      "id": "P036",
      "group": "2020-2021",
      "title": "Multi-dimensional Pruning: A Unified Framework for Model Compression",
      "authors": "Jinyang Guo, Wanli Ouyang, Dong Xu",
      "venue": "IEEE Conference on Computer Vision and Pattern Recognition (CVPR), 2020.",
      "year": 2020,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://openaccess.thecvf.com/content_CVPR_2020/html/Guo_Multi-Dimensional_Pruning_A_Unified_Framework_for_Model_Compression_CVPR_2020_paper.html",
      "code_link": "",
      "book_link": "",
      "award": "",
      "featured": true,
      "cover_image": ""
    },
    {
      "id": "P037",
      "group": "2025",
      "title": "HarmoniCa: Harmonizing Training and Inference for Better Feature Caching in Diffusion Transformer Acceleration",
      "authors": "Yushi Huang, Zining Wang, Ruihao Gong, Jing Liu, Xinjie Zhang, Jinyang Guo, Xianglong Liu, Jun Zhang",
      "venue": "Forty-second International Conference on Machine Learning (ICML), 2025.",
      "year": 2025,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://proceedings.mlr.press/v267/huang25ah.html",
      "code_link": "https://github.com/ModelTC/HarmoniCa",
      "book_link": "",
      "award": "",
      "tags": "ICML 2025, Diffusion, Feature Caching, Diffusion Transformer, Acceleration",
      "featured": true,
      "cover_image": "",
      "intro_md_cn": "publications/md/harmonica-harmonizing-training-and-inference-for-better-feature-caching-in-diffusion-transformer-acceleration_cn.md",
      "intro_md_en": "publications/md/harmonica-harmonizing-training-and-inference-for-better-feature-caching-in-diffusion-transformer-acceleration_en.md"
    },
    {
      "id": "P038",
      "group": "2025",
      "title": "Temporal Feature Matters: A Framework for Diffusion Model Quantization",
      "authors": "Yushi Huang, Ruihao Gong, Xianglong Liu, Jing Liu, Yuhang Li, Jiwen Lu, Dacheng Tao",
      "venue": "IEEE Transactions on Pattern Analysis and Machine Intelligence (TPAMI), 2025.",
      "year": 2025,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://arxiv.org/abs/2407.19547",
      "code_link": "",
      "book_link": "",
      "award": "",
      "tags": "TPAMI 2025, Diffusion, Quantization, Temporal Feature, PTQ",
      "featured": true,
      "cover_image": "",
      "intro_md_cn": "publications/md/temporal-feature-matters-a-framework-for-diffusion-model-quantization_cn.md",
      "intro_md_en": "publications/md/temporal-feature-matters-a-framework-for-diffusion-model-quantization_en.md"
    },
    {
      "id": "P039",
      "group": "2024",
      "title": "Accurate LoRA-Finetuning Quantization of LLMs via Information Retention",
      "authors": "Haotong Qin, Xudong Ma, Xingyu Zheng, Xiaoyang Li, Yang Zhang, Shouda Liu, Jie Luo, Xianglong Liu, Michele Magno",
      "venue": "Forty-first International Conference on Machine Learning (ICML), 2024.",
      "year": 2024,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://proceedings.mlr.press/v235/qin24b.html",
      "code_link": "https://github.com/htqin/IR-QLoRA",
      "book_link": "",
      "award": "",
      "tags": "ICML 2024, LLM, Quantization, LoRA, Fine-Tuning",
      "featured": true,
      "cover_image": "",
      "intro_md_cn": "publications/md/accurate-lora-finetuning-quantization-of-llms-via-information-retention_cn.md",
      "intro_md_en": "publications/md/accurate-lora-finetuning-quantization-of-llms-via-information-retention_en.md"
    },
    {
      "id": "P040",
      "group": "2024",
      "title": "BiLLM: Pushing the Limit of Post-Training Quantization for LLMs",
      "authors": "Wei Huang, Yangdong Liu, Haotong Qin, Ying Li, Shiming Zhang, Xianglong Liu, Michele Magno, Xiaojuan Qi",
      "venue": "Forty-first International Conference on Machine Learning (ICML), 2024.",
      "year": 2024,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://proceedings.mlr.press/v235/huang24q.html",
      "code_link": "",
      "book_link": "",
      "award": "",
      "tags": "ICML 2024, LLM, Quantization, Binarization, PTQ",
      "featured": true,
      "cover_image": "",
      "intro_md_cn": "publications/md/billm-pushing-the-limit-of-post-training-quantization-for-llms_cn.md",
      "intro_md_en": "publications/md/billm-pushing-the-limit-of-post-training-quantization-for-llms_en.md"
    },
    {
      "id": "P041",
      "group": "2024",
      "title": "TFMQ-DM: Temporal Feature Maintenance Quantization for Diffusion Models",
      "authors": "Yushi Huang, Ruihao Gong, Jing Liu, Tianlong Chen, Xianglong Liu",
      "venue": "IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR), 2024.",
      "year": 2024,
      "citations": 0,
      "scholar_link": "",
      "paper_link": "https://arxiv.org/abs/2311.16503",
      "code_link": "https://github.com/ModelTC/TFMQ-DM",
      "book_link": "",
      "award": "Highlight Poster",
      "tags": "CVPR 2024, Diffusion, Quantization, Temporal Feature, PTQ",
      "featured": true,
      "cover_image": "",
      "intro_md_cn": "publications/md/tfmq-dm-temporal-feature-maintenance-quantization-for-diffusion-models_cn.md",
      "intro_md_en": "publications/md/tfmq-dm-temporal-feature-maintenance-quantization-for-diffusion-models_en.md"
    }
  ]
};
